### ISSUE TITLE
SLMX4 Health App link doesn't work

### ISSUE THREAD

**Issue by flatearth-tidd** [SensorLogicInc/modules#3]
[SLMX4 Health App link](https://modules-release.s3-us-west-2.amazonaws.com/health_windows_app/slmx4_health_ui_usb.zip) throws an error.

![image](https://user-images.githubusercontent.com/47638889/106550794-164cb380-64d1-11eb-8e25-03c7700a74bf.png)

**Comment by dack-fe** [comment]
@flatearth-tidd @flatearth-hadella After uploading the new app to S3, the zip file has to be made publicly available.
