### ISSUE TITLE
Is the Radar board detachable?

### ISSUE THREAD

**Issue by wangziqi000** [SensorLogicInc/modules#9]
Hi，

I was previously doing development using X4M05 and Raspberry Pi (SPI), which was unfortunately discontinued. I happen to notice that this new board (SLMX4) is also using X4 and similar pins. I wonder if it will be possible to detach the radar board from the MCU and continue to develop using Raspberry Pi SPI. 

Any help is appreciated!
Sincerely

**Comment by flatearth-tidd** [comment]
Yes, it matches the pinout of the X4A02 on the X4M05.

-will
